config/routes.rb
Rails.application.routes.draw do
  get "users/show"
  devise_for :users
  root 'homes#index'
  resources :reservations
  resources :hairstyles
  
  resources :items do
    resources :purchases, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 1, name: '性別を選んで下さい'},
    { id: 2, name: 'レディース'},
    { id: 3, name: 'メンズ'}
  ]

  include ActiveHash::Associations
  has_many :hairstyles

end

app/models/haircolor.rb
class Haircolor < ActiveHash::Base
  self.data = [
    { id: 1, name: '髪色を選んで下さい'},
    { id: 2, name: 'ブラック'},
    { id: 3, name: 'ナチュラルブラウン'},
    { id: 4, name: 'アッシュブラウン'},
    { id: 5, name: 'ピンクブラウン'},
    { id: 6, name: 'シルバー'},
    { id: 7, name: 'ブルー'},
    { id: 8, name: 'ピンク'},
    { id: 9, name: 'その他'}
  ]

  include ActiveHash::Associations
  has_many :hairstyles

end

app/models/hairlength.rb
class Hairlength < ActiveHash::Base
  self.data = [
    { id: 1, name: '髪の長さを選んで下さい'},
    { id: 2, name: 'ベリーショート'},
    { id: 3, name: 'ショート'},
    { id: 4, name: 'ショートミディアム'},
    { id: 5, name: 'ミディアム'},
    { id: 6, name: 'ロング'},
    { id: 7, name: 'ボウズ'}
  ]

  include ActiveHash::Associations
  has_many :hairstyles

end

app/models/hairstyle.rb
class Hairstyle < ApplicationRecord

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :gender
  belongs_to_active_hash :hairlength
  belongs_to_active_hash :haircolor

  belongs_to :user
  has_one_attached :image

  with_options presence: true do
    validates :image
    validates :hairstylename
    validates :detail
  end

  with_options numericality: { other_than: 1 } do
    validates :gender_id
    validates :hairlength_id
    validates :haircolor_id
  end
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/menu.rb
class Menu < ActiveHash::Base
  self.data = [
    { id: 1, name: 'メニューを選んで下さい'},
    { id: 2, name: 'カット(1時間)'},
    { id: 3, name: 'カラー(2時間)'},
    { id: 4, name: 'ダブルカラー(2.5時間)'},
    { id: 5, name: '縮毛矯正(3時間)'}
  ]

  include ActiveHash::Associations
  has_many :reservations

end

app/models/purchase.rb
class Purchase < ApplicationRecord
end

app/models/reservation.rb
class Reservation < ApplicationRecord

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :menu
  belongs_to :user

  validates :day, presence: true
  validates :time, presence: true
  validates :start_time, presence: true, uniqueness: true

  with_options numericality: { other_than: 1 } do
    validates :menu_id
  end

  def self.check_reservation_day(day)
    if day < Date.current
      return "過去の日付は選択できません。正しい日付を選択してください。"
    elsif (Date.current >> 3) < day
      return "3ヶ月以降の日付は選択できません。正しい日付を選択してください。"
    end
  end

  def self.reservations_after_three_month
    reservations = Reservation.all.where("day >= ?", Date.current).where("day < ?", Date.current >> 3).order(day: :desc)
    reservation_data = []
    reservations.each do |reservation|
      reservations_hash = {}
      reservations_hash.merge!(day: reservation.day.strftime("%Y-%m-%d"), time: reservation.time)
      reservation_data.push(reservations_hash)
    end
    reservation_data
  end
end

app/models/stock.rb
class Stock < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reservations , dependent: :destroy
  has_many :hairstyles , dependent: :destroy
end

app/controllers/hairstyles_controller.rb
class HairstylesController < ApplicationController
  before_action :authenticate_user! ,except: [:index,:show]
  before_action :hairstyle_find ,only: [:show, :edit, :update, :destroy]
  before_action :user_check ,only: [:edit, :update, :destroy]

  def index
    @hairstyles = Hairstyle.all.includes(:user)
  end

  def show
  end

  def new
    @hairstyle = Hairstyle.new
  end

  def create
    @hairstyle = Hairstyle.create(hairstyle_params)
    if @hairstyle.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @hairstyle.update(hairstyle_params)
      redirect_to hairstyle_path(@hairstyle.id)
    else
      render :edit
    end
  end

  def destroy
    @hairstyle.destroy
    redirect_to root_path
  end


  private

  def hairstyle_find
    @hairstyle = Hairstyle.find(params[:id])
  end

  def hairstyle_params
    params.require(:hairstyle).permit(:hairstylename, :gender_id, :hairlength_id, :haircolor_id, :detail, :image).merge(user_id: current_user.id)
  end

  def user_check
    unless @hairstyle.user_id == current_user.id
      redirect_to action: :index
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def destroy
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(current_user.id)
    @user_reservations = current_user.reservations.where("start_time >= ?", DateTime.current).order(day: :asc)
    @visit_historys = current_user.reservations.where("start_time < ?", DateTime.current).where("start_time > ?", DateTime.current << 12).order(day: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hairstyles_helper.rb
module HairstylesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
  def times
    times = ["10:00",
             "11:00",
             "12:00",
             "13:00",
             "14:00",
             "15:00",
             "16:00",
             "17:00",
             "18:00",
             "19:00",
             "20:00"
            ]
  end

  def check_reservation(reservations, day, time)
    result = false
    reservations_count = reservations.count
    if reservations_count > 1
      reservations.each do |reservation|
        result = reservation[:day].eql?(day.strftime("%Y-%m-%d")) && reservation[:time].eql?(time)
        return result if result
      end
    elsif reservations_count == 1
      result = reservations[0][:day].eql?(day.strftime("%Y-%m-%d")) && reservations[0][:time].eql?(time)
      return result if result
    end
    return result
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hairstyles/edit.html.erb
<%= form_with model: @hairstyle, local: true do |f| %>
 <div class="container">
    <h1>ヘアスタイル編集</h1>
    <label>ヘアスタイル名 <span class="badge badge-danger">必須</span></label>
    <%= f.text_field :hairstylename, autofocus: true, class:"form-control", placeholder:"ヘアスタイル名" %>
    <label>ヘアスタイルについて <span class="badge badge-danger">必須</span></label>
    <%= f.text_area :detail, class:"form-control", placeholder:"ヘアスタイルについて" %>
    <label>性別 <span class="badge badge-danger">必須</span></label>
    <%= f.collection_select(:gender_id, Gender.all, :id, :name, {}, {class:"form-control"}) %>
    <label>髪の長さ <span class="badge badge-danger">必須</span></label>
    <%= f.collection_select(:hairlength_id, Hairlength.all, :id, :name, {}, {class:"form-control"}) %>
    <label>髪の色 <span class="badge badge-danger">必須</span></label>
    <%= f.collection_select(:haircolor_id, Haircolor.all, :id, :name, {}, {class:"form-control"}) %>
      <div class="field">
        <%= f.label :image, "ヘアスタイル写真" %> <span class="badge badge-danger">必須</span> <br>
        <%= f.file_field :image, id:"hairstyle_image" ,class:"form-control" %>
      </div>
    <br>
    <%= f.submit "編集を完了する" ,class:"btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/hairstyles/index.html.erb
<div class='main'>
  <div class='hairstyle-contents'>
    <h2 class='title'>ヘアスタイル一覧</h2>
    <div class="subtitle" >
      最近の流行り
    </div>
    <ul class='hairstyle-lists'>
      <% @hairstyles.each do |hairstyle| %>
      <li class='list'>
        <%= link_to hairstyle_path(hairstyle.id) do %>
        <div class='hairstyle-img-content'>
          <%= image_tag hairstyle.image, class: "hairstyle-img" %>

        </div>
        <div class='hairstyle-info'>
          <h3 class='hairstyle-hairstylename'>
            <%= hairstyle.hairstylename %>
          </h3>
          <div class='hairstyle-detail'>
            <%= hairstyle.detail %>
          </div>
        </div>
        <% end %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/hairstyles/new.html.erb
<%= form_with model: @hairstyle, url:hairstyles_path, local: true do |f| %>
  <div class="container">
    <br>
    <h1>ヘアスタイル投稿</h1>
    <br>
    <label>ヘアスタイル名 <span class="badge badge-danger">必須</span></label>
    <%= f.text_field :hairstylename, autofocus: true, class:"form-control", placeholder:"ヘアスタイル名" %>
    <br>
    <label>ヘアスタイルについて <span class="badge badge-danger">必須</span></label>
    <%= f.text_area :detail, class:"form-control", placeholder:"ヘアスタイルについて" %>
    <br>
    <label>性別 <span class="badge badge-danger">必須</span></label>
    <%= f.collection_select(:gender_id, Gender.all, :id, :name, {}, {class:"form-control"}) %>
    <br>
    <label>髪の長さ <span class="badge badge-danger">必須</span></label>
    <%= f.collection_select(:hairlength_id, Hairlength.all, :id, :name, {}, {class:"form-control"}) %>
    <br>
    <label>髪の色 <span class="badge badge-danger">必須</span></label>
    <%= f.collection_select(:haircolor_id, Haircolor.all, :id, :name, {}, {class:"form-control"}) %>
    <br>
      <div class="field">
        <%= f.label :image, "ヘアスタイル写真" %> <span class="badge badge-danger">必須</span> <br>
        <%= f.file_field :image, id:"hairstyle_image" ,class:"form-control" %>
      </div>
    <br>
    <%= f.submit "投稿する" ,class:"btn btn-primary btn-block" %>
  </div>

<% end %>

app/views/hairstyles/show.html.erb
<div class="hairstyle-show">
  <div class="hairstyle-box">
    <h2 class="hairstylename">
      <%= @hairstyle.hairstylename %>
    </h2>
    <br>
    <div class="hairstyle-img-content">
      <%= image_tag @hairstyle.image ,class:"hairstyle-box-img" %>
    </div>
    <hr>
    <% if user_signed_in?%>
      <% if current_user.id == @hairstyle.user_id %>
        <%= link_to "編集", edit_hairstyle_path, method: :get, class: "btn btn-primary btn-block" %>
        <p class="or-text">or</p>
        <%= link_to "削除", hairstyle_path(@hairstyle.id), method: :delete, class:"btn btn-danger btn-block" %>
      <% else %>
        <%= link_to "予約画面に進む", reservations_path ,class:"btn btn-primary btn-block"%>
      <% end %>
    <% end %>
    <hr>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-hairstyle">ヘアスタイルについて</th>
          <td class="detail-value"><%= @hairstyle.detail %></td>
        </tr>
        <tr>
          <th class="detail-hairstyle">性別</th>
          <td class="detail-value"><%= @hairstyle.gender.name %></td>
        </tr>
        <tr>
          <th class="detail-hairstyle">髪の長さ</th>
          <td class="detail-value"><%= @hairstyle.hairlength.name %></td>
        </tr>
        <tr>
          <th class="detail-hairstyle">髪の色</th>
          <td class="detail-value"><%= @hairstyle.haircolor.name %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/user/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-center title">
      <h1>マイページ</h1>
    </div>
    <div class="col-12 mt-3 text-center content">
      <div>
        <label><strong>名前：</strong></label>
        <p style="display:inline;"><%= @user.name %></p>
      </div>
      <div>
        <label><strong>メールアドレス：</strong></label>
        <p style="display:inline;"><%= @user.email %></p>
      </div>
      <div class="col-12 mt-3 text-center mx-auto">
        <h3>予約一覧</h3>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">予約日</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @user_reservations.each do |user_reservation| %>
              <td>
                <%= user_reservation.day %>
                <%= user_reservation.time %>              
              </td>
              <td>
                <%= link_to '削除', reservation_path(user_reservation.id), method: :delete, data: { confirm: "削除してよろしいですか？", commit: "削除する", cancel: "やめる", title: "ご確認ください" } %>
              </td>
            </tr>             
            <% end %>
            <% if @user_reservations.blank? %>
              <tr>
                <td>予約はありません。</td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-12 mt-3 text-center mx-auto">
        <h3>来院履歴</h3>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">予約日</th>
            </tr>
          </thead>
          <tbody>
            <% @visit_historys.each do |visit_history| %>
              <tr>
                <td>
                  <%= visit_history.day %>
                  <%= visit_history.time %>              
                </td>
              </tr>
            <% end %>
            <% if @visit_historys.blank? %>
              <tr>
                <td>来院履歴はありません。</td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-center title">
      <br>
      <h1>マイページ</h1>
    </div>
    <div class="col-12 mt-3 text-center content">
      <div>
        <label><strong>メールアドレス：</strong></label>
        <p style="display:inline;"><%= @user.email %></p>
      </div>
      <div class="col-12 mt-3 text-center mx-auto">
        <h3>予約一覧</h3>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">予約日</th>
            </tr>
          </thead>
          <tbody>
            <% @user_reservations.each do |user_reservation| %>
              <td>
                <%= user_reservation.day %>
                <%= user_reservation.time %>              
              </td>
            </tr>             
            <% end %>
            <% if @user_reservations.blank? %>
              <tr>
                <td>予約はありません。</td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-12 mt-3 text-center mx-auto">
        <h3>ご利用履歴</h3>
        <table class="table">
          <thead>
            <tr>
              <th scope="col12">予約日</th>
            </tr>
          </thead>
          <tbody>
            <% @visit_historys.each do |visit_history| %>
              <tr>
                <td>
                  <%= visit_history.day %>
                  <%= visit_history.time %>              
                </td>
              </tr>
            <% end %>
            <% if @visit_historys.blank? %>
              <tr>
                <td>ご利用履歴はありません。</td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>